package gca1;
/*
 * 
 * You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

b[0] is equal to a[0];
b[1] is equal to the last element of a;
b[2] is equal to a[1];
b[3] is equal to the second-last element of a;
b[4] is equal to a[2];
b[5] is equal to the third-last element of a;
and so on.
Here is how this process works:

 */
public class AlternatingSort {

	public static void main(String[] args) {
		int[] a = new int[] {-92, -23, 0, 45, 89, 96, 99, 95, 89, 41, -17, -48};
		int[] b = new int[a.length];
		
		System.out.println( alternatingSort(a));
		
	}

	private static boolean alternatingSort(int[] a) {
		int[] c = new int[a.length];
		
		for (int i = 0, k=0; i < a.length; i+=2,k++) {
			c[i] = a[k];
			if(i != 0) {
				if(c[i - 1] >= c[i]) return false;
			}
			if(i <= a.length - 2) {
				c[i + 1] = a[a.length - 1 - k];
				if(c[i] >= c[i + 1]) return false;
			}
			
 		}
		
		return true;
	}
}
