/*
 * https://www.hackerrank.com/contests/projecteuler/challenges/euler002/problem
 * 
 * 
 * ---Question---
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed N,  find the sum of the even-valued terms.
 * 
 * Input Format
 * First line contains  T that denotes the number of test cases. This is followed by T lineseach containing an integer, N.
 * 
 * 
 * 
 * --Turkish--
 * Fibonacci serisinde N olarak belirtilen sayiya kadar olan cift sayilarin toplamini bulmamiz gerekiyor. 
 * Yani 
 * input olarak 10 girildiyse , 2 + 8 = 10
 * input olarak 100 girildiyse , 2 + 8 + 34 = 44  
 * 
 */
package codingcompetitions.projecteuler;

import java.util.Scanner;

public class A2_EvenFibonacciNumbers {

	public static void main(String[] args) {

		Scanner in = new Scanner(System.in);
		int t = in.nextInt();
		for (int a0 = 0; a0 < t; a0++) {
			long n = in.nextLong();
			System.out.println(sumOfEvenFibonacciNumbers(n));
		}

	}

	private static long sumOfEvenFibonacciNumbers(long topNumber) {
		// ilk iki fibonacci rakamini manuel verip kalanini hesaplayarak bulacagiz
		long sum = 0;
		long secondToLast = 0;
		long firstToLast = 1;
		long newFibonacciNumber = secondToLast + firstToLast;

		
		 // while dongusu icinde buldugumuz yeni fibonacci sayisi , methoda verilen N sayisindan buyuk olmadigi surece dongu islemeye devam edicek
		do {

			// son bulunan fibonacci sayisi cift ise, toplami tuttugumuz variable a	atariz.
			if (newFibonacciNumber % 2 == 0) {
				sum += newFibonacciNumber;
			}

			
			 // eldeki son iki fibonacci sayisini toplayip, yeni fibonacci sayisini buluyoruz ve son ikiyi tuttugumuz variable lari yeni degerleri ile guncelliyoruz
			newFibonacciNumber = secondToLast + firstToLast;
			secondToLast = firstToLast;
			firstToLast = newFibonacciNumber;
		} while (newFibonacciNumber <= topNumber);
		return sum;
	}

	/*
	 * Bir baska yaklasim
	 * 
	 * Fibonacci serisinde cift olan sayilarin arasinda belli bir pattern bulunuyor
	 * 
	 * 0, 2, 8, 34, 144, 610, 2584, 10946.
	 * 
	 * Bir sonraki cift fibonacci sayisi = 4 * sonCiftFib + sondanIkinciCiftFib
	 * 8 = 4 * 2 + 0 
	 * 144 = 4 * 34 + 8 
	 * 610 = 4 * 144 + 34
	 * ...
	 * 
	 */
/*	private static long sumOfEvenFibonacciNumbers(long topNumber) {
		if(topNumber < 2 ) return 0;
		long sum = 2;
		long secondToLastEvenFib = 0;
		long firstToLastEvenFib = 2;
		long newEvenFib = 4 * firstToLastEvenFib + secondToLastEvenFib;
		do{
			sum += newEvenFib;
			secondToLastEvenFib = firstToLastEvenFib;
			firstToLastEvenFib = newEvenFib;
			newEvenFib = 4 * firstToLastEvenFib + secondToLastEvenFib;
		} while(newEvenFib <= topNumber);
		
		return sum;
	}*/

}
